name: Diff to Webhook

on:
  push:
    branches: [main]  # Déclenche sur les pushes vers main

jobs:
  diff_and_notify:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout du code
        uses: actions/checkout@v3
        with:
          fetch-depth: 2  # Nécessaire pour obtenir le commit précédent

      - name: Envoyer le diff au webhook
        run: |
          WEBHOOK_URL="https://discord.com/api/webhooks/1395666955201150986/-4CYXIpa5HsCyiXAS5vD1FmZ056xZDVnioNKf8RVPUgy1KIKZLW6v3KMiZr51xkDr5TQ"
          FILE="regles.md"
          MAX_DISCORD_LEN=1900
          
          # 1. Obtenir la diff légère : uniquement lignes ajoutées/supprimées
          # - ignorer les lignes commençant par '@' (en-têtes de bloc)
          # - ignorer les lignes de contexte (sans + ou -)
          # - conserver uniquement les lignes ajoutées/supprimées
          git diff HEAD^ HEAD -- "$FILE" \
            | grep -E '^[+-]' \
            | grep -vE '^\+\+\+|^---' \
            > filtered.diff
          
          # 2. Lire le contenu dans une variable
          DIFF_CONTENT=$(cat filtered.diff)
          
          # 3. Découper et paginer
          LENGTH=${#DIFF_CONTENT}
          CHUNK_COUNT=$(( (LENGTH + MAX_DISCORD_LEN - 1) / MAX_DISCORD_LEN ))
          
          for (( i=0; i<CHUNK_COUNT; i++ ))
          do
            START=$(( i * MAX_DISCORD_LEN ))
            CHUNK="${DIFF_CONTENT:$START:$MAX_DISCORD_LEN}"
          
            # Préparer le message avec le format Discord
            PAGE=$((i+1))
            MESSAGE="Diff pour \`$FILE\` (page $PAGE/$CHUNK_COUNT):\n\`\`\`diff\n$CHUNK\n\`\`\`"
          
            # Envoyer le message à Discord
            curl -s -X POST "$WEBHOOK_URL" \
              -H "Content-Type: application/json" \
              -d @<(jq -n --arg content "$MESSAGE" '{content: $content}')
          
            sleep 1  # Évite le rate-limit
          done
          
          # 4. Message de confirmation
          curl -s -X POST "$WEBHOOK_URL" \
            -H "Content-Type: application/json" \
            -d '{"content": "Fin de la diff"}'

