name: Send Diff to Discord

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  send-diff:
    runs-on: ubuntu-latest
    environment: production

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: Install jq
        run: sudo apt-get install -y jq

      - name: Run custom Discord diff action
        uses: ./.github/actions/discord-diff
        env:
          webhook_url: ${{ secrets.DISCORD_WEBHOOK }}
          file: 'regles.md'
